/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChartsPreviewRouteImport } from './routes/charts-preview'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated/superadmin'
import { Route as ApiEmailExportAllRouteImport } from './routes/api/email-export-all'
import { Route as ApiExtractRouteImport } from './routes/api/extract'
import { Route as ApiQueueExtractionsRouteImport } from './routes/api/queue-extractions'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedAdminAnomaliesRouteImport } from './routes/_authenticated/admin.anomalies'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin.billing'
import { Route as AuthenticatedAdminBrandRouteImport } from './routes/_authenticated/admin.brand'
import { Route as AuthenticatedAdminCommissionsRouteImport } from './routes/_authenticated/admin.commissions'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin.employees'
import { Route as AuthenticatedAdminLeaderboardRouteImport } from './routes/_authenticated/admin.leaderboard'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin.partners'
import { Route as AuthenticatedAdminPayoutsRouteImport } from './routes/_authenticated/admin.payouts'
import { Route as AuthenticatedAdminReconciliationRouteImport } from './routes/_authenticated/admin.reconciliation'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminStoresRouteImport } from './routes/_authenticated/admin.stores'
import { Route as AuthenticatedAdminUnassignedRouteImport } from './routes/_authenticated/admin.unassigned'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminWorkspaceRouteImport } from './routes/_authenticated/admin.workspace'
import { Route as AuthenticatedBatchesIndexRouteImport } from './routes/_authenticated/batches.index'
import { Route as AuthenticatedBatchesIdRouteImport } from './routes/_authenticated/batches.$id'
import { Route as AuthenticatedBatchesNewRouteImport } from './routes/_authenticated/batches.new'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding.index'
import { Route as AuthenticatedOnboardingPlanRouteImport } from './routes/_authenticated/onboarding.plan'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedPortalPerformanceRouteImport } from './routes/_authenticated/portal.performance'
import { Route as AuthenticatedPortalStatementsRouteImport } from './routes/_authenticated/portal.statements'
import { Route as AuthenticatedSuperadminBillingRouteImport } from './routes/_authenticated/superadmin.billing'
import { Route as ApiEmailExportBatchIdRouteImport } from './routes/api/email-export.$batchId'
import { Route as ApiExportBatchIdRouteImport } from './routes/api/export.$batchId'
import { Route as ApiPublicInngestRouteImport } from './routes/api/public/inngest'
import { Route as AuthenticatedAdminEmployeesIdRouteImport } from './routes/_authenticated/admin.employees.$id'
import { Route as AuthenticatedAdminPartnersIdRouteImport } from './routes/_authenticated/admin.partners.$id'
import { Route as AuthenticatedAdminPerformancePartnerIdRouteImport } from './routes/_authenticated/admin.performance.$partnerId'
import { Route as AuthenticatedAdminStatementsPartnerIdRouteImport } from './routes/_authenticated/admin.statements.$partnerId'
import { Route as ApiPublicHooksMonthCloseRouteImport } from './routes/api/public/hooks/month-close'
import { Route as ApiPublicHooksRolloverPayoutsRouteImport } from './routes/api/public/hooks/rollover-payouts'
import { Route as ApiPublicHooksRunScheduledReportsRouteImport } from './routes/api/public/hooks/run-scheduled-reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsPreviewRoute = ChartsPreviewRouteImport.update({
  id: '/charts-preview',
  path: '/charts-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiEmailExportAllRoute = ApiEmailExportAllRouteImport.update({
  id: '/api/email-export-all',
  path: '/api/email-export-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueueExtractionsRoute = ApiQueueExtractionsRouteImport.update({
  id: '/api/queue-extractions',
  path: '/api/queue-extractions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAdminAnomaliesRoute =
  AuthenticatedAdminAnomaliesRouteImport.update({
    id: '/admin/anomalies',
    path: '/admin/anomalies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/admin/billing',
    path: '/admin/billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBrandRoute = AuthenticatedAdminBrandRouteImport.update({
  id: '/admin/brand',
  path: '/admin/brand',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCommissionsRoute =
  AuthenticatedAdminCommissionsRouteImport.update({
    id: '/admin/commissions',
    path: '/admin/commissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/admin/employees',
    path: '/admin/employees',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLeaderboardRoute =
  AuthenticatedAdminLeaderboardRouteImport.update({
    id: '/admin/leaderboard',
    path: '/admin/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/admin/partners',
    path: '/admin/partners',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPayoutsRoute =
  AuthenticatedAdminPayoutsRouteImport.update({
    id: '/admin/payouts',
    path: '/admin/payouts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReconciliationRoute =
  AuthenticatedAdminReconciliationRouteImport.update({
    id: '/admin/reconciliation',
    path: '/admin/reconciliation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStoresRoute =
  AuthenticatedAdminStoresRouteImport.update({
    id: '/admin/stores',
    path: '/admin/stores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUnassignedRoute =
  AuthenticatedAdminUnassignedRouteImport.update({
    id: '/admin/unassigned',
    path: '/admin/unassigned',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminWorkspaceRoute =
  AuthenticatedAdminWorkspaceRouteImport.update({
    id: '/admin/workspace',
    path: '/admin/workspace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBatchesIndexRoute =
  AuthenticatedBatchesIndexRouteImport.update({
    id: '/batches/',
    path: '/batches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBatchesIdRoute = AuthenticatedBatchesIdRouteImport.update({
  id: '/batches/$id',
  path: '/batches/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBatchesNewRoute = AuthenticatedBatchesNewRouteImport.update({
  id: '/batches/new',
  path: '/batches/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingPlanRoute =
  AuthenticatedOnboardingPlanRouteImport.update({
    id: '/onboarding/plan',
    path: '/onboarding/plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/portal/',
    path: '/portal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalPerformanceRoute =
  AuthenticatedPortalPerformanceRouteImport.update({
    id: '/portal/performance',
    path: '/portal/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalStatementsRoute =
  AuthenticatedPortalStatementsRouteImport.update({
    id: '/portal/statements',
    path: '/portal/statements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperadminBillingRoute =
  AuthenticatedSuperadminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)
const ApiEmailExportBatchIdRoute = ApiEmailExportBatchIdRouteImport.update({
  id: '/api/email-export/$batchId',
  path: '/api/email-export/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportBatchIdRoute = ApiExportBatchIdRouteImport.update({
  id: '/api/export/$batchId',
  path: '/api/export/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInngestRoute = ApiPublicInngestRouteImport.update({
  id: '/api/public/inngest',
  path: '/api/public/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminEmployeesIdRoute =
  AuthenticatedAdminEmployeesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminEmployeesRoute,
  } as any)
const AuthenticatedAdminPartnersIdRoute =
  AuthenticatedAdminPartnersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPartnersRoute,
  } as any)
const AuthenticatedAdminPerformancePartnerIdRoute =
  AuthenticatedAdminPerformancePartnerIdRouteImport.update({
    id: '/admin/performance/$partnerId',
    path: '/admin/performance/$partnerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStatementsPartnerIdRoute =
  AuthenticatedAdminStatementsPartnerIdRouteImport.update({
    id: '/admin/statements/$partnerId',
    path: '/admin/statements/$partnerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksMonthCloseRoute =
  ApiPublicHooksMonthCloseRouteImport.update({
    id: '/api/public/hooks/month-close',
    path: '/api/public/hooks/month-close',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRolloverPayoutsRoute =
  ApiPublicHooksRolloverPayoutsRouteImport.update({
    id: '/api/public/hooks/rollover-payouts',
    path: '/api/public/hooks/rollover-payouts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunScheduledReportsRoute =
  ApiPublicHooksRunScheduledReportsRouteImport.update({
    id: '/api/public/hooks/run-scheduled-reports',
    path: '/api/public/hooks/run-scheduled-reports',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/charts-preview': typeof ChartsPreviewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/superadmin': typeof AuthenticatedSuperadminRouteWithChildren
  '/api/email-export-all': typeof ApiEmailExportAllRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/queue-extractions': typeof ApiQueueExtractionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/anomalies': typeof AuthenticatedAdminAnomaliesRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/brand': typeof AuthenticatedAdminBrandRoute
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRouteWithChildren
  '/admin/leaderboard': typeof AuthenticatedAdminLeaderboardRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRouteWithChildren
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/reconciliation': typeof AuthenticatedAdminReconciliationRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/admin/unassigned': typeof AuthenticatedAdminUnassignedRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/workspace': typeof AuthenticatedAdminWorkspaceRoute
  '/batches/$id': typeof AuthenticatedBatchesIdRoute
  '/batches/new': typeof AuthenticatedBatchesNewRoute
  '/onboarding/plan': typeof AuthenticatedOnboardingPlanRoute
  '/portal/performance': typeof AuthenticatedPortalPerformanceRoute
  '/portal/statements': typeof AuthenticatedPortalStatementsRoute
  '/superadmin/billing': typeof AuthenticatedSuperadminBillingRoute
  '/api/email-export/$batchId': typeof ApiEmailExportBatchIdRoute
  '/api/export/$batchId': typeof ApiExportBatchIdRoute
  '/api/public/inngest': typeof ApiPublicInngestRoute
  '/batches/': typeof AuthenticatedBatchesIndexRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/employees/$id': typeof AuthenticatedAdminEmployeesIdRoute
  '/admin/partners/$id': typeof AuthenticatedAdminPartnersIdRoute
  '/admin/performance/$partnerId': typeof AuthenticatedAdminPerformancePartnerIdRoute
  '/admin/statements/$partnerId': typeof AuthenticatedAdminStatementsPartnerIdRoute
  '/api/public/hooks/month-close': typeof ApiPublicHooksMonthCloseRoute
  '/api/public/hooks/rollover-payouts': typeof ApiPublicHooksRolloverPayoutsRoute
  '/api/public/hooks/run-scheduled-reports': typeof ApiPublicHooksRunScheduledReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/charts-preview': typeof ChartsPreviewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/superadmin': typeof AuthenticatedSuperadminRouteWithChildren
  '/api/email-export-all': typeof ApiEmailExportAllRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/queue-extractions': typeof ApiQueueExtractionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/anomalies': typeof AuthenticatedAdminAnomaliesRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/brand': typeof AuthenticatedAdminBrandRoute
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRouteWithChildren
  '/admin/leaderboard': typeof AuthenticatedAdminLeaderboardRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRouteWithChildren
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/reconciliation': typeof AuthenticatedAdminReconciliationRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/admin/unassigned': typeof AuthenticatedAdminUnassignedRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/workspace': typeof AuthenticatedAdminWorkspaceRoute
  '/batches/$id': typeof AuthenticatedBatchesIdRoute
  '/batches/new': typeof AuthenticatedBatchesNewRoute
  '/onboarding/plan': typeof AuthenticatedOnboardingPlanRoute
  '/portal/performance': typeof AuthenticatedPortalPerformanceRoute
  '/portal/statements': typeof AuthenticatedPortalStatementsRoute
  '/superadmin/billing': typeof AuthenticatedSuperadminBillingRoute
  '/api/email-export/$batchId': typeof ApiEmailExportBatchIdRoute
  '/api/export/$batchId': typeof ApiExportBatchIdRoute
  '/api/public/inngest': typeof ApiPublicInngestRoute
  '/batches': typeof AuthenticatedBatchesIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/employees/$id': typeof AuthenticatedAdminEmployeesIdRoute
  '/admin/partners/$id': typeof AuthenticatedAdminPartnersIdRoute
  '/admin/performance/$partnerId': typeof AuthenticatedAdminPerformancePartnerIdRoute
  '/admin/statements/$partnerId': typeof AuthenticatedAdminStatementsPartnerIdRoute
  '/api/public/hooks/month-close': typeof ApiPublicHooksMonthCloseRoute
  '/api/public/hooks/rollover-payouts': typeof ApiPublicHooksRolloverPayoutsRoute
  '/api/public/hooks/run-scheduled-reports': typeof ApiPublicHooksRunScheduledReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/charts-preview': typeof ChartsPreviewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/superadmin': typeof AuthenticatedSuperadminRouteWithChildren
  '/api/email-export-all': typeof ApiEmailExportAllRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/queue-extractions': typeof ApiQueueExtractionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/admin/anomalies': typeof AuthenticatedAdminAnomaliesRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/brand': typeof AuthenticatedAdminBrandRoute
  '/_authenticated/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRouteWithChildren
  '/_authenticated/admin/leaderboard': typeof AuthenticatedAdminLeaderboardRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRouteWithChildren
  '/_authenticated/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/_authenticated/admin/reconciliation': typeof AuthenticatedAdminReconciliationRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/_authenticated/admin/unassigned': typeof AuthenticatedAdminUnassignedRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/workspace': typeof AuthenticatedAdminWorkspaceRoute
  '/_authenticated/batches/$id': typeof AuthenticatedBatchesIdRoute
  '/_authenticated/batches/new': typeof AuthenticatedBatchesNewRoute
  '/_authenticated/onboarding/plan': typeof AuthenticatedOnboardingPlanRoute
  '/_authenticated/portal/performance': typeof AuthenticatedPortalPerformanceRoute
  '/_authenticated/portal/statements': typeof AuthenticatedPortalStatementsRoute
  '/_authenticated/superadmin/billing': typeof AuthenticatedSuperadminBillingRoute
  '/api/email-export/$batchId': typeof ApiEmailExportBatchIdRoute
  '/api/export/$batchId': typeof ApiExportBatchIdRoute
  '/api/public/inngest': typeof ApiPublicInngestRoute
  '/_authenticated/batches/': typeof AuthenticatedBatchesIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/employees/$id': typeof AuthenticatedAdminEmployeesIdRoute
  '/_authenticated/admin/partners/$id': typeof AuthenticatedAdminPartnersIdRoute
  '/_authenticated/admin/performance/$partnerId': typeof AuthenticatedAdminPerformancePartnerIdRoute
  '/_authenticated/admin/statements/$partnerId': typeof AuthenticatedAdminStatementsPartnerIdRoute
  '/api/public/hooks/month-close': typeof ApiPublicHooksMonthCloseRoute
  '/api/public/hooks/rollover-payouts': typeof ApiPublicHooksRolloverPayoutsRoute
  '/api/public/hooks/run-scheduled-reports': typeof ApiPublicHooksRunScheduledReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/charts-preview'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard'
    | '/notifications'
    | '/orders'
    | '/reports'
    | '/search'
    | '/superadmin'
    | '/api/email-export-all'
    | '/api/extract'
    | '/api/queue-extractions'
    | '/auth/callback'
    | '/admin/anomalies'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/brand'
    | '/admin/commissions'
    | '/admin/employees'
    | '/admin/leaderboard'
    | '/admin/partners'
    | '/admin/payouts'
    | '/admin/reconciliation'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/unassigned'
    | '/admin/users'
    | '/admin/workspace'
    | '/batches/$id'
    | '/batches/new'
    | '/onboarding/plan'
    | '/portal/performance'
    | '/portal/statements'
    | '/superadmin/billing'
    | '/api/email-export/$batchId'
    | '/api/export/$batchId'
    | '/api/public/inngest'
    | '/batches/'
    | '/onboarding/'
    | '/portal/'
    | '/admin/employees/$id'
    | '/admin/partners/$id'
    | '/admin/performance/$partnerId'
    | '/admin/statements/$partnerId'
    | '/api/public/hooks/month-close'
    | '/api/public/hooks/rollover-payouts'
    | '/api/public/hooks/run-scheduled-reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/charts-preview'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard'
    | '/notifications'
    | '/orders'
    | '/reports'
    | '/search'
    | '/superadmin'
    | '/api/email-export-all'
    | '/api/extract'
    | '/api/queue-extractions'
    | '/auth/callback'
    | '/admin/anomalies'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/brand'
    | '/admin/commissions'
    | '/admin/employees'
    | '/admin/leaderboard'
    | '/admin/partners'
    | '/admin/payouts'
    | '/admin/reconciliation'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/unassigned'
    | '/admin/users'
    | '/admin/workspace'
    | '/batches/$id'
    | '/batches/new'
    | '/onboarding/plan'
    | '/portal/performance'
    | '/portal/statements'
    | '/superadmin/billing'
    | '/api/email-export/$batchId'
    | '/api/export/$batchId'
    | '/api/public/inngest'
    | '/batches'
    | '/onboarding'
    | '/portal'
    | '/admin/employees/$id'
    | '/admin/partners/$id'
    | '/admin/performance/$partnerId'
    | '/admin/statements/$partnerId'
    | '/api/public/hooks/month-close'
    | '/api/public/hooks/rollover-payouts'
    | '/api/public/hooks/run-scheduled-reports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/charts-preview'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/orders'
    | '/_authenticated/reports'
    | '/_authenticated/search'
    | '/_authenticated/superadmin'
    | '/api/email-export-all'
    | '/api/extract'
    | '/api/queue-extractions'
    | '/auth/callback'
    | '/_authenticated/admin/anomalies'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/brand'
    | '/_authenticated/admin/commissions'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/leaderboard'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/payouts'
    | '/_authenticated/admin/reconciliation'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/stores'
    | '/_authenticated/admin/unassigned'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/workspace'
    | '/_authenticated/batches/$id'
    | '/_authenticated/batches/new'
    | '/_authenticated/onboarding/plan'
    | '/_authenticated/portal/performance'
    | '/_authenticated/portal/statements'
    | '/_authenticated/superadmin/billing'
    | '/api/email-export/$batchId'
    | '/api/export/$batchId'
    | '/api/public/inngest'
    | '/_authenticated/batches/'
    | '/_authenticated/onboarding/'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/employees/$id'
    | '/_authenticated/admin/partners/$id'
    | '/_authenticated/admin/performance/$partnerId'
    | '/_authenticated/admin/statements/$partnerId'
    | '/api/public/hooks/month-close'
    | '/api/public/hooks/rollover-payouts'
    | '/api/public/hooks/run-scheduled-reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ChartsPreviewRoute: typeof ChartsPreviewRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiEmailExportAllRoute: typeof ApiEmailExportAllRoute
  ApiExtractRoute: typeof ApiExtractRoute
  ApiQueueExtractionsRoute: typeof ApiQueueExtractionsRoute
  ApiEmailExportBatchIdRoute: typeof ApiEmailExportBatchIdRoute
  ApiExportBatchIdRoute: typeof ApiExportBatchIdRoute
  ApiPublicInngestRoute: typeof ApiPublicInngestRoute
  ApiPublicHooksMonthCloseRoute: typeof ApiPublicHooksMonthCloseRoute
  ApiPublicHooksRolloverPayoutsRoute: typeof ApiPublicHooksRolloverPayoutsRoute
  ApiPublicHooksRunScheduledReportsRoute: typeof ApiPublicHooksRunScheduledReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts-preview': {
      id: '/charts-preview'
      path: '/charts-preview'
      fullPath: '/charts-preview'
      preLoaderRoute: typeof ChartsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin': {
      id: '/_authenticated/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/email-export-all': {
      id: '/api/email-export-all'
      path: '/api/email-export-all'
      fullPath: '/api/email-export-all'
      preLoaderRoute: typeof ApiEmailExportAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queue-extractions': {
      id: '/api/queue-extractions'
      path: '/api/queue-extractions'
      fullPath: '/api/queue-extractions'
      preLoaderRoute: typeof ApiQueueExtractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/admin/anomalies': {
      id: '/_authenticated/admin/anomalies'
      path: '/admin/anomalies'
      fullPath: '/admin/anomalies'
      preLoaderRoute: typeof AuthenticatedAdminAnomaliesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/brand': {
      id: '/_authenticated/admin/brand'
      path: '/admin/brand'
      fullPath: '/admin/brand'
      preLoaderRoute: typeof AuthenticatedAdminBrandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/commissions': {
      id: '/_authenticated/admin/commissions'
      path: '/admin/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AuthenticatedAdminCommissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/leaderboard': {
      id: '/_authenticated/admin/leaderboard'
      path: '/admin/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AuthenticatedAdminLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payouts': {
      id: '/_authenticated/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reconciliation': {
      id: '/_authenticated/admin/reconciliation'
      path: '/admin/reconciliation'
      fullPath: '/admin/reconciliation'
      preLoaderRoute: typeof AuthenticatedAdminReconciliationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/stores': {
      id: '/_authenticated/admin/stores'
      path: '/admin/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AuthenticatedAdminStoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/unassigned': {
      id: '/_authenticated/admin/unassigned'
      path: '/admin/unassigned'
      fullPath: '/admin/unassigned'
      preLoaderRoute: typeof AuthenticatedAdminUnassignedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/workspace': {
      id: '/_authenticated/admin/workspace'
      path: '/admin/workspace'
      fullPath: '/admin/workspace'
      preLoaderRoute: typeof AuthenticatedAdminWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/batches/': {
      id: '/_authenticated/batches/'
      path: '/batches'
      fullPath: '/batches/'
      preLoaderRoute: typeof AuthenticatedBatchesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/batches/$id': {
      id: '/_authenticated/batches/$id'
      path: '/batches/$id'
      fullPath: '/batches/$id'
      preLoaderRoute: typeof AuthenticatedBatchesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/batches/new': {
      id: '/_authenticated/batches/new'
      path: '/batches/new'
      fullPath: '/batches/new'
      preLoaderRoute: typeof AuthenticatedBatchesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/plan': {
      id: '/_authenticated/onboarding/plan'
      path: '/onboarding/plan'
      fullPath: '/onboarding/plan'
      preLoaderRoute: typeof AuthenticatedOnboardingPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/performance': {
      id: '/_authenticated/portal/performance'
      path: '/portal/performance'
      fullPath: '/portal/performance'
      preLoaderRoute: typeof AuthenticatedPortalPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/statements': {
      id: '/_authenticated/portal/statements'
      path: '/portal/statements'
      fullPath: '/portal/statements'
      preLoaderRoute: typeof AuthenticatedPortalStatementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin/billing': {
      id: '/_authenticated/superadmin/billing'
      path: '/billing'
      fullPath: '/superadmin/billing'
      preLoaderRoute: typeof AuthenticatedSuperadminBillingRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
    '/api/email-export/$batchId': {
      id: '/api/email-export/$batchId'
      path: '/api/email-export/$batchId'
      fullPath: '/api/email-export/$batchId'
      preLoaderRoute: typeof ApiEmailExportBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/$batchId': {
      id: '/api/export/$batchId'
      path: '/api/export/$batchId'
      fullPath: '/api/export/$batchId'
      preLoaderRoute: typeof ApiExportBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inngest': {
      id: '/api/public/inngest'
      path: '/api/public/inngest'
      fullPath: '/api/public/inngest'
      preLoaderRoute: typeof ApiPublicInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/employees/$id': {
      id: '/_authenticated/admin/employees/$id'
      path: '/$id'
      fullPath: '/admin/employees/$id'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesIdRouteImport
      parentRoute: typeof AuthenticatedAdminEmployeesRoute
    }
    '/_authenticated/admin/partners/$id': {
      id: '/_authenticated/admin/partners/$id'
      path: '/$id'
      fullPath: '/admin/partners/$id'
      preLoaderRoute: typeof AuthenticatedAdminPartnersIdRouteImport
      parentRoute: typeof AuthenticatedAdminPartnersRoute
    }
    '/_authenticated/admin/performance/$partnerId': {
      id: '/_authenticated/admin/performance/$partnerId'
      path: '/admin/performance/$partnerId'
      fullPath: '/admin/performance/$partnerId'
      preLoaderRoute: typeof AuthenticatedAdminPerformancePartnerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/statements/$partnerId': {
      id: '/_authenticated/admin/statements/$partnerId'
      path: '/admin/statements/$partnerId'
      fullPath: '/admin/statements/$partnerId'
      preLoaderRoute: typeof AuthenticatedAdminStatementsPartnerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/month-close': {
      id: '/api/public/hooks/month-close'
      path: '/api/public/hooks/month-close'
      fullPath: '/api/public/hooks/month-close'
      preLoaderRoute: typeof ApiPublicHooksMonthCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/rollover-payouts': {
      id: '/api/public/hooks/rollover-payouts'
      path: '/api/public/hooks/rollover-payouts'
      fullPath: '/api/public/hooks/rollover-payouts'
      preLoaderRoute: typeof ApiPublicHooksRolloverPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-scheduled-reports': {
      id: '/api/public/hooks/run-scheduled-reports'
      path: '/api/public/hooks/run-scheduled-reports'
      fullPath: '/api/public/hooks/run-scheduled-reports'
      preLoaderRoute: typeof ApiPublicHooksRunScheduledReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSuperadminRouteChildren {
  AuthenticatedSuperadminBillingRoute: typeof AuthenticatedSuperadminBillingRoute
}

const AuthenticatedSuperadminRouteChildren: AuthenticatedSuperadminRouteChildren =
  {
    AuthenticatedSuperadminBillingRoute: AuthenticatedSuperadminBillingRoute,
  }

const AuthenticatedSuperadminRouteWithChildren =
  AuthenticatedSuperadminRoute._addFileChildren(
    AuthenticatedSuperadminRouteChildren,
  )

interface AuthenticatedAdminEmployeesRouteChildren {
  AuthenticatedAdminEmployeesIdRoute: typeof AuthenticatedAdminEmployeesIdRoute
}

const AuthenticatedAdminEmployeesRouteChildren: AuthenticatedAdminEmployeesRouteChildren =
  {
    AuthenticatedAdminEmployeesIdRoute: AuthenticatedAdminEmployeesIdRoute,
  }

const AuthenticatedAdminEmployeesRouteWithChildren =
  AuthenticatedAdminEmployeesRoute._addFileChildren(
    AuthenticatedAdminEmployeesRouteChildren,
  )

interface AuthenticatedAdminPartnersRouteChildren {
  AuthenticatedAdminPartnersIdRoute: typeof AuthenticatedAdminPartnersIdRoute
}

const AuthenticatedAdminPartnersRouteChildren: AuthenticatedAdminPartnersRouteChildren =
  {
    AuthenticatedAdminPartnersIdRoute: AuthenticatedAdminPartnersIdRoute,
  }

const AuthenticatedAdminPartnersRouteWithChildren =
  AuthenticatedAdminPartnersRoute._addFileChildren(
    AuthenticatedAdminPartnersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSuperadminRoute: typeof AuthenticatedSuperadminRouteWithChildren
  AuthenticatedAdminAnomaliesRoute: typeof AuthenticatedAdminAnomaliesRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminBrandRoute: typeof AuthenticatedAdminBrandRoute
  AuthenticatedAdminCommissionsRoute: typeof AuthenticatedAdminCommissionsRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRouteWithChildren
  AuthenticatedAdminLeaderboardRoute: typeof AuthenticatedAdminLeaderboardRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRouteWithChildren
  AuthenticatedAdminPayoutsRoute: typeof AuthenticatedAdminPayoutsRoute
  AuthenticatedAdminReconciliationRoute: typeof AuthenticatedAdminReconciliationRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStoresRoute: typeof AuthenticatedAdminStoresRoute
  AuthenticatedAdminUnassignedRoute: typeof AuthenticatedAdminUnassignedRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWorkspaceRoute: typeof AuthenticatedAdminWorkspaceRoute
  AuthenticatedBatchesIdRoute: typeof AuthenticatedBatchesIdRoute
  AuthenticatedBatchesNewRoute: typeof AuthenticatedBatchesNewRoute
  AuthenticatedOnboardingPlanRoute: typeof AuthenticatedOnboardingPlanRoute
  AuthenticatedPortalPerformanceRoute: typeof AuthenticatedPortalPerformanceRoute
  AuthenticatedPortalStatementsRoute: typeof AuthenticatedPortalStatementsRoute
  AuthenticatedBatchesIndexRoute: typeof AuthenticatedBatchesIndexRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedAdminPerformancePartnerIdRoute: typeof AuthenticatedAdminPerformancePartnerIdRoute
  AuthenticatedAdminStatementsPartnerIdRoute: typeof AuthenticatedAdminStatementsPartnerIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRouteWithChildren,
  AuthenticatedAdminAnomaliesRoute: AuthenticatedAdminAnomaliesRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminBrandRoute: AuthenticatedAdminBrandRoute,
  AuthenticatedAdminCommissionsRoute: AuthenticatedAdminCommissionsRoute,
  AuthenticatedAdminEmployeesRoute:
    AuthenticatedAdminEmployeesRouteWithChildren,
  AuthenticatedAdminLeaderboardRoute: AuthenticatedAdminLeaderboardRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRouteWithChildren,
  AuthenticatedAdminPayoutsRoute: AuthenticatedAdminPayoutsRoute,
  AuthenticatedAdminReconciliationRoute: AuthenticatedAdminReconciliationRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStoresRoute: AuthenticatedAdminStoresRoute,
  AuthenticatedAdminUnassignedRoute: AuthenticatedAdminUnassignedRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWorkspaceRoute: AuthenticatedAdminWorkspaceRoute,
  AuthenticatedBatchesIdRoute: AuthenticatedBatchesIdRoute,
  AuthenticatedBatchesNewRoute: AuthenticatedBatchesNewRoute,
  AuthenticatedOnboardingPlanRoute: AuthenticatedOnboardingPlanRoute,
  AuthenticatedPortalPerformanceRoute: AuthenticatedPortalPerformanceRoute,
  AuthenticatedPortalStatementsRoute: AuthenticatedPortalStatementsRoute,
  AuthenticatedBatchesIndexRoute: AuthenticatedBatchesIndexRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedAdminPerformancePartnerIdRoute:
    AuthenticatedAdminPerformancePartnerIdRoute,
  AuthenticatedAdminStatementsPartnerIdRoute:
    AuthenticatedAdminStatementsPartnerIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ChartsPreviewRoute: ChartsPreviewRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiEmailExportAllRoute: ApiEmailExportAllRoute,
  ApiExtractRoute: ApiExtractRoute,
  ApiQueueExtractionsRoute: ApiQueueExtractionsRoute,
  ApiEmailExportBatchIdRoute: ApiEmailExportBatchIdRoute,
  ApiExportBatchIdRoute: ApiExportBatchIdRoute,
  ApiPublicInngestRoute: ApiPublicInngestRoute,
  ApiPublicHooksMonthCloseRoute: ApiPublicHooksMonthCloseRoute,
  ApiPublicHooksRolloverPayoutsRoute: ApiPublicHooksRolloverPayoutsRoute,
  ApiPublicHooksRunScheduledReportsRoute:
    ApiPublicHooksRunScheduledReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
